### ISSUE TITLE
 Don't know how to configure and display thisvid video

### ISSUE THREAD

**Issue by hezhushizaishi** [AAndyProgram/SCrawler#146]
Hi this is my first time asking a question on GitHub and I'm a beginner,I configured the settings of thisvid according to your method, but the content of the user does not appear,the first one is mine and the second one is my friend's, but none of the posts appear,I don't know where the problem is and I don't know how to fix it, so I'm bothering you.
<img width="779" alt="12" src="https://github.com/AAndyProgram/SCrawler/assets/122086865/03be65f2-f1b2-4544-8a28-0aab4b9ecfe1">

I would like to take this opportunity to ask you if it is possible to download private videos even without being friends.Because you didn't say it very carefully, is the private video of being a friend or anyone, and the private [video](url) of not being a friend is encrypted,

Thanks for taking the time to answer my question, thank you very much.

**Comment by pingzoo** [comment]
I hope it's ok if I reply to it, because ThisVid is the only provider I got running :D

What happens when you start the download? Is there an error or success message and are there entries in the LOG? I have attached two snippets here. From my ThisVid settings and from a user.
User:
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/ef0cf77c-a8ea-42c1-8073-00b26db9476e)
Settings:
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/eb6d26c7-bc6d-4355-9786-ce69e9e4e3f2)

If you then right-click on the user and click "Download Data", the download should begin and download the files in the directory you specified. This process can take quite some time.
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/788fc05b-02ca-4f23-9aeb-450a7eaf19f7)

In the status bar you can see if the SCrawler is working.
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/5335e0d8-7c17-4feb-987a-cc5b5e86d866)

Regarding your 2nd question: Downloading private videos is only possible from friends if you are logged in with a browser and have imported the cookies from there into the scrawler.

**Comment by AAndyProgram** [comment]
@pingzoo's answer is correct. Thank you for the help.

>I don't know where the problem is and I don't know how to fix it

In addition to cookies, ThisVid also [requires](https://github.com/AAndyProgram/SCrawler/wiki/Settings#thisvid-requirements) `yt-dlp`. `yt-dlp`, in turn, requires `ffmpeg` and `ffprobe`. Please make sure that the correct paths to the programs are specified in the [settings](https://github.com/AAndyProgram/SCrawler/wiki/Settings#environment).

This profile (https://thisvid.com/members/3717551/) contains only one private video. You must be a friend of this member to view and/or download this video.

This profile (https://thisvid.com/members/3057511/) contains 1 public video and 7 private videos. You must be a friend of this member to view and/or download private videos. **I downloaded the public video without any problems.**

>if it is possible to download private videos even without being friends

No, they are protected. As @pingzoo said: **you must be a friend of this member to view and/or download private videos.**

>private [video](https://github.com/AAndyProgram/SCrawler/issues/url) of not being a friend is encrypted

They are not encrypted. They are protected.

**Comment by hezhushizaishi** [comment]
> I hope it's ok if I reply to it, because ThisVid is the only provider I got running :D
> 
> What happens when you start the download? Is there an error or success message and are there entries in the LOG? I have attached two snippets here. From my ThisVid settings and from a user. User: ![image](https://user-images.githubusercontent.com/56318476/246375272-ef0cf77c-a8ea-42c1-8073-00b26db9476e.png) Settings: ![image](https://user-images.githubusercontent.com/56318476/246375547-eb6d26c7-bc6d-4355-9786-ce69e9e4e3f2.png)
> 
> If you then right-click on the user and click "Download Data", the download should begin and download the files in the directory you specified. This process can take quite some time. ![image](https://user-images.githubusercontent.com/56318476/246376243-788fc05b-02ca-4f23-9aeb-450a7eaf19f7.png)
> 
> In the status bar you can see if the SCrawler is working. ![image](https://user-images.githubusercontent.com/56318476/246376640-5335e0d8-7c17-4feb-987a-cc5b5e86d866.png)
> 
> Regarding your 2nd question: Downloading private videos is only possible from friends if you are logged in with a browser and have imported the cookies from there into the scrawler.


I am so happy to receive a reply soon, and then I refer to the configuration you gave, it is the same, that is, the default configuration，
Then I clicked Download data according to your instructions, for the first account, there is a download progress bar just like you said, but the data is not updated, and it is the same for the second account.

So I tried to click Download data limited, which is also the default value, and found that the first one has no data, but the second one has it! However, it only downloaded half of the data.
Please forgive me that I am not a native speaker of English, and I am a real beginner, and I can't master English very well.

So I don't know how to mobilize the log, but it is indeed able to download the video, if you need the log, I can try to learn,
Another point, I guess you have brought ffmpeg and other applications, because I have installed them before and configured the environment. According to the manual you wrote, I changed yt-dlp into my own yt-dlp, and everything else no change.I don't know if it matters,

Finally, I really appreciate you replying me so quickly. I feel that the question I asked is a basic tutorial. I feel very embarrassed because it is really too basic. You have such detailed information, but it is really difficult for me to understand. If you are busy and bored, I don’t want to bother you, because I feel guilty for wasting such a simple problem as a novice. If you guys don't mind, I'll spend my free time debugging and discussing to master this software as much as I can, really appreciate you seeing this, thanks.

**Comment by pingzoo** [comment]
Hey @hezhushizaishi

No need to be embarrassed. Who can help helps. Who has no time does not help. I'm just getting to know the program as a new user and would like to help you, or share my experiences with you.

But to be honest, I may not be able to help you here, because I also sometimes have difficulties using the program and spend a lot of time with "trial and error".

Maybe the following hints will help you:

1. i have downloaded and unpacked the latest release. I did not install or modify any of the additional programs like ffmpeg or yt-dpl myself. The release downloaded here includes all the programs and the scrawler has set the paths correctly itself.

2. if during the download of media from a ThisVid user an error occurs, or I cancel the download, a new download does not work. SCrawler responds with a pop-up that the data has been completely downloaded, even though the state is the same as when I canceled the last download.

In this case it helped me to delete one of the files, so that SCrawler starts the download from the beginning. It detected which files were already present and skipped them.
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/c9fa30d8-d265-4b66-9d91-fc9bd14783f9)

If I am at all stuck I delete the user and create it again
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/9c749fc8-9880-486d-8a66-2fc421b92495)
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/4cbdcda1-b15a-4ee0-b7e4-f5f6dfeb0c3b)

Attention, you delete the complete user including all previously downloaded media.

But to be clear: I'm still trying to understand myself in which cases the program behaves how. I'm just sharing my experience with you. It may be that my suggestions here are wrong, or there are better solutions :)

So now I would suggest you to delete the user in SCrawler, create it again and start the download again. Be patient and give SCrawler time to work. Don't abort the process early ;) Then wait until there is no running job in the status bar and the program responds with a success message or an error message and finishes the download. Then check if all the files you expected have been downloaded. If not all media are present, you can call the LOG via the button "LOG":
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/5d1b21bd-69bc-4d59-9876-35d689086a23)

The older LOGs can be found in the program directory in the subdirectory "LOGs":
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/c414c6d1-b233-49f2-879c-878cc6a6c1ab)

I wish you much success and would be happy about a feedback ;)
My English is also terrible by the way :) Deepl and its apps and browser extension have become my friend ;)

**Comment by AAndyProgram** [comment]
@hezhushizaishi 
@pingzoo is right, no need to be embarrassed. If you have a problem, post it. If you have a question, ask it. I answer everyone who asks questions.

> So I tried to click Download data limited, which is also the default value, and found that the first one has no data, but the second one has it! However, it only downloaded half of the data.

`Download data limited` is a [feature](https://github.com/AAndyProgram/SCrawler/wiki#context-menu) to download a certain number of first posts. The number of posts to be downloaded is set by the user when he clicks on this button.

Please read the [guide](https://github.com/AAndyProgram/SCrawler/wiki) carefully. You can use Google Translate to translate the guide into your native language.

**Keep in mind that SCrawler takes time to collect post information and download each video. The size of some videos can be really huge.**

> Then I clicked Download data according to your instructions, for the first account, there is a download progress bar just like you said, but the data is not updated, and it is the same for the second account.

If you download this user once, SCrawler will store the processed post IDs. When you download that user again and the downloader sees the already processed post ID, that post will be skipped. This allows SCrwler to only download new posts.

> So I don't know how to mobilize the log, but it is indeed able to download the video, if you need the log, I can try to learn,
Another point, I guess you have brought ffmpeg and other applications, because I have installed them before and configured the environment

The complete environment required for SCrawler is included in the release.

> According to the manual you wrote, I changed yt-dlp into my own yt-dlp, and everything else no change.I don't know if it matters,

If you didn't change the "environment" path included in the release, you don't need to change the paths. Correct operation is guaranteed only with the environment included in the release.

----

@pingzoo 
> In this case it helped me to delete one of the files, so that SCrawler starts the download from the beginning. It detected which files were already present and skipped them.

Correct.

> If I am at all stuck I delete the user and create it again

Look, if there is a problem, you should post it here and I will do my best to fix it if the problem persists and I can repeat the error. Deleting a user to re-add to fix some bugs isn't the right way to interact with SCrawler. You're just making your SCrawler experience much harder.

> But to be clear: I'm still trying to understand myself in which cases the program behaves how

The algorithm for deleting a user is shown in the [diagram](https://github.com/AAndyProgram/SCrawler/wiki#deleting-a-user).

Please read the [guide](https://github.com/AAndyProgram/SCrawler/wiki) carefully.
