### ISSUE TITLE
Uncomlpete xHamster downloads w/o error or LOG

### ISSUE THREAD

**Issue by pingzoo** [AAndyProgram/SCrawler#149]
Hey,

probably again only with me, but I have also with xHamster the problem that SCrawler finds only a part of the posts. Even though you may not be able to reproduce it, I still wanted to inform you about it.

If you have time, you can check it out:

https://xhamster.com/users/jens15
Videos: 43
Public: 30

Scrawler found 43
[1st Job - Found 43 - User_XHamster_jens15_Posts.txt](https://github.com/AAndyProgram/SCrawler/files/11841718/1st.Job.-.Found.43.-.User_XHamster_jens15_Posts.txt)

Scrawler dowloaded 23
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/076b09df-7f29-45f1-98ab-0735cd44a01d)

Scrawler added 21 to Data.xml
[User_XHamster_jens15_Data.txt](https://github.com/AAndyProgram/SCrawler/files/11841883/User_XHamster_jens15_Data.txt)

Deleted Posts.txt, started download again.
SCrawler found 23 Posts (exactly the 23 Posts that are already downloaded)
[User_XHamster_jens15_Posts.txt](https://github.com/AAndyProgram/SCrawler/files/11841922/User_XHamster_jens15_Posts.txt)

Example of a post that is first found but not downloaded in 1st job and not found in 2nd job:
https://xhamster.com/videos/soft-hard-soft-hard-12897272
If I add this URL to the Downloader I get this:
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/2500921b-4e71-4cf8-91e4-53ab58835758)
But no Video is loaded.

**Comment by AAndyProgram** [comment]
I'm sorry but I've downloaded all of this user's public videos. Video "Soft hard soft hard" is number 5 from the top.
Excuse me but are you sure you have free space enough to download these videos?

![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/a32d2f6d-97be-4c40-b8b0-ea8033d98c2b)

**Comment by pingzoo** [comment]
Hmm weird.
Yes I have >400GB free space. And the download with other tools (for example Chrome Extension Video DownloadHelper) works fine. I have this problem with almost all users. This is really strange :(

If you are interested, you can watch it here (6 minutes)
https://drive.google.com/file/d/1BBnyCNLdCEKqKiPbrn64OLRv4QsOX1ID/view?usp=sharing

**Comment by AAndyProgram** [comment]
I saw your video. Of course I don't think you're lying. I don't know what to say. I can download all videos. In your video, the "Log" button is highlighted in red. What data is in the log?

**Comment by AAndyProgram** [comment]
Have you added cookies for xHamster?

**Comment by pingzoo** [comment]
The log sais "missing posts".
If I download the missing posts SCrawler send a Notification "All data downloaded"

Yes, i've exportet the cookies from chrome as JSON and imported them in SCrawler.
They are working, i've checked it by manipulating the language-cookie.

![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/c2e54754-e52d-4aa2-92c1-1ad11a9a0f2d)
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/25187c67-47a6-4d78-a581-8781362c0a27)
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/d40b039a-0f42-4ff6-a591-f74366ccb851)


yt-dlp can't find all fragments

One of the 23 working vids:
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/c82320f3-cf0a-407d-b102-608f81929ae3)

soft hard soft hard:
![image](https://github.com/AAndyProgram/SCrawler/assets/56318476/dc57136a-61b3-4e66-9a0f-53bda25f7bd2)

**Comment by AAndyProgram** [comment]
I don't use yt-dlp to download xHamstter data.

**Comment by pingzoo** [comment]
Yeah ok. But I think yt-dlp queries the same m3u8 and the errors with yt-dlp happen exactly with the files SCrawler doesn't download either. And if yt-dlp doesn't find the fragments, SCrawler will have the same problem.

Just funny that this happens with me, although with you the download works great.

I'm really sorry that I bothered you again, although the problem seems to be with me.

If you can do me one last favor. Would you try if yt-dlp finishes the download successfully for you?
CMD
yt-dlp.exe "https://xhamster.com/videos/soft-hard-soft-hard-12897272"

**Comment by AAndyProgram** [comment]
> But I think yt-dlp queries the same m3u8 and the errors with yt-dlp happen exactly with the files SCrawler doesn't download either. And if yt-dlp doesn't find the fragments, SCrawler will have the same problem.

I haven't seen the xhamster extractor code for ytt, so I don't know how exactly it gets the m3u8. I also don't know how it handles errors. My code throws an error if some parts of the file cannot be downloaded. By default, the missing posts errors is disabled in the [settings](https://github.com/AAndyProgram/SCrawler/wiki/Settings#downloading). You can turn them on to see what happened: `Settings` - `Downloading` - `Add missing errors to log`. Try enabling this setting and try downloading again. Maybe we will see something new. :-)

> If you can do me one last favor. Would you try if yt-dlp finishes the download successfully for you?
> CMD
> yt-dlp.exe "https://xhamster.com/videos/soft-hard-soft-hard-12897272"

At your request, I used yt-dlp to download this video. The video download was successful. Additionally, in cmd, you can see the cmd code page (chcp = 65001) and the yt-dlp version (2023.03.04).

![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/92ddb10e-9e0f-43a7-8d4d-0604ffb6b695)

![image](https://github.com/AAndyProgram/SCrawler/assets/88590076/bd58059f-c4f4-4ee6-a085-19cd5d3f6c2f)

**Comment by AAndyProgram** [comment]
I noticed that yt-dlp downloaded the mp4 file and not the m3u8. So I decided to download the m3u8 file. The video download was successful.

yt-dlp log:

```bat
d:\tmpData>yt-dlp --list-formats https://xhamster.com/videos/soft-hard-soft-hard-12897272
[XHamster] Extracting URL: https://xhamster.com/videos/soft-hard-soft-hard-12897272
[XHamster] 12897272: Downloading webpage
[XHamster] 12897272: Downloading m3u8 information
[info] Available formats for 12897272:
ID       EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC
───────────────────────────────────────────────────────────────────────────────────
mp4-144p mp4 144p           │   13.21MiB       https │ unknown           unknown
hls-95   mp4 256x144     30 │ ~ 13.39MiB   95k m3u8  │ avc1.4d401e   95k video only
mp4-240p mp4 240p           │   38.52MiB       https │ unknown           unknown
hls-280  mp4 426x240     30 │ ~ 39.31MiB  280k m3u8  │ avc1.42c01f  280k video only
mp4-480p mp4 480p           │   96.13MiB       https │ unknown           unknown
hls-700  mp4 854x480     30 │ ~ 98.29MiB  700k m3u8  │ avc1.640029  700k video only
mp4-720p mp4 720p           │  167.51MiB       https │ unknown           unknown
hls-1220 mp4 1280x720    30 │ ~171.38MiB 1221k m3u8  │ avc1.640029 1221k video only

d:\tmpData>yt-dlp --verbose -f "bv*[format_id=hls-1220]" https://xhamster.com/videos/soft-hard-soft-hard-12897272 -P "d:\tmpData"
[debug] Command-line config: ['--verbose', '-f', 'bv*[format_id=hls-1220]', 'https://xhamster.com/videos/soft-hard-soft-hard-12897272', '-P', 'd:\\tmpData']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[XHamster] Extracting URL: https://xhamster.com/videos/soft-hard-soft-hard-12897272
[XHamster] 12897272: Downloading webpage
[XHamster] 12897272: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 12897272: Downloading 1 format(s): hls-1220
[debug] Invoking hlsnative downloader on "https://19-18.b.cdn13.com/hls/bsd/4000/sd/4000/012/897/272/720p.h264.mp4/index-v1.m3u8?cdn_hash=9a38b7e85bbefe2a79b15b&cdn_creation_time=1687504182&cdn_ttl=14400&cdn_cv_data=<ip-address>-dvp"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 288
[download] Destination: d:\tmpData\Soft hard soft hard [12897272].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of  175.71MiB in 00:02:29 at 1.18MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:d:\tmpData\Soft hard soft hard [12897272].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "d:\tmpData\Soft hard soft hard [12897272].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:d:\tmpData\Soft hard soft hard [12897272].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:d:\tmpData\Soft hard soft hard [12897272].temp.mp4"

d:\tmpData>
```

![Capture](https://github.com/AAndyProgram/SCrawler/assets/88590076/90064150-7051-4557-b037-2b386035d6ac)

**Comment by pingzoo** [comment]
Hey dude. 
Thank you so much for your research!
 I'm at work right now.  I'll have a look at it later

**Comment by AAndyProgram** [comment]
@pater-p 

This profile again? I already told you both that I successfully [downloaded](https://github.com/AAndyProgram/SCrawler/issues/149#issuecomment-1603632992) this profile. I want to help both of you, really, but I don't know how. The logs don't makes thing any clearer. I can download this profile and don't see the error.

I don't know why you both have this problem. Have you used a VPN?

**1a**. The `Attempts` value indicates the number of failed attempts to download the file. `1` means one failed attempt

**1b**. Yes and no. By default, SCrawler, in order to reduce the number of unnecessary requests to the site (mainly to protect your account, but also to reduce download time), makes one attempt to download file. If the file was not downloaded, when the download is complete, you will see a message in the log: `Some posts didn't download. You can see them in the 'Missing posts' form.`. If you review the log you posted (Log 1), you will see this message in the last text line. But SCrawler can also download missing posts during routine. **To enable this feature (disabled by default), enable the `Trying to download missing posts using regular download` option in the settings.**

You can read about "Missing posts" here: https://github.com/AAndyProgram/SCrawler/wiki#missing-posts

**2**. "States" is a state of the post. It means what the SCrawler did with the particular post.

2 means `Downloaded`
4 means `Missing`

https://github.com/AAndyProgram/SCrawler/blob/bade8666d5646ae56918459d3353656d04e98ad2/SCrawler/API/Base/Structures.vb#L39

"Type" is the content type of the post. Types can be combined.

https://github.com/AAndyProgram/SCrawler/blob/bade8666d5646ae56918459d3353656d04e98ad2/SCrawler/API/Base/Structures.vb#L28-L38

**3**. The `....._Posts.txt` list contains all the posts that SCrawler sees. This allows SCrawler to only download posts that have not been viewed. The `....._Data.xml` list contains only posts that have been downloaded and/or should be downloaded.

**4**. I answered this in answer **1b**. Personally, I prefer to use the missing posts form to download missing stuff. But you can enable this option. If so, the missing posts will retry to download each time you download this profile. This may take time.

**5**. Favorite posts only.

> Is there any other way to sponsor you a cup coffee?

Thank you. Your kind words are enough. I used to use 'buymeacoffee' site, but I have a problem with PayPal. This site also allows you to connect to Stripe, but I have no idea how that works. At all. So I don't really want to waste my time trying to find service that I understand. PayPal is dead to me. But most of them use PayPal.

**Comment by AAndyProgram** [comment]
Could it be the antivirus? Try adding SCrawler, ffmpeg, yt-dlp, gallery-dl and other environment programs to your antivirus exceptions.
