### ISSUE TITLE
[NSFW] Not sure if this is grabbing all data from Reddit users

### ISSUE THREAD

**Issue by BluesFanUK** [AAndyProgram/SCrawler#196]
Been using this for about a year and just let it do its thing in the background, I have several hundred gigs downloaded now, but just out of curiosity I wanted to test it was working ok, I stumbled on an account with a reasonably small size of data to look at without being overly active:

https://www.reddit.com/user/kg_soles/

SCrawler has downloaded around around 70 images going back to September 2022 and i've deleted duplicates.

There are no videos though, so it's missing this one, and the pink sock one (take your pic from the old.reddit link).
https://www.reddit.com/r/VerifiedFeet/comments/x6qwqb/my_feet_need_attention/
https://old.reddit.com/user/kg_soles/submitted/?count=450&after=t3_woh5fw

I have a load of missing posts (likely imgur/deleted reddit posts), but none from this user, so i'm stumped. No matter how many times I ask SCrawler to download from the user it doesn't pick up any of these. I've a sneaky suspicion this isn't downloading from v.reddit fullstop!

**Comment by AAndyProgram** [comment]
I can't find a bug downloading this profile. The profile downloading is complete for me. I found a bug in the `ReparseMissing` function when trying to download missing posts. This will be fixed in the next version. Try using [OAuth](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-get-reddit-credentials)+Cookies. Don't forget to check the `Use the token to download the timeline` and `Use cookies to download the timeline` checkboxes.

----

**Join our Discord server**: https://discord.gg/uFNUXvFFmg

**Comment by BluesFanUK** [comment]
Got both check boxes already ticked and I've registered is under the reddit app.

Removed the entire data set and settings, re added it and still no videos. I don't understand how you managed to get them but I can't?
