### ISSUE TITLE
[REQUEST] SCrawler does not check system environment variables for ffmpeg

### ISSUE THREAD

**Issue by reichbc** [AAndyProgram/SCrawler#73]
**Describe the bug**
When starting the program, it tells me "ffmpeg.exe is missing" despite the program being installed on my machine and being in the PATH variable systemwide.

**Expected behavior**
Program should check local folder first for the existence of ffmpeg.exe, and then it should check user and system environment variables to see if it exists elsewhere on the system.

**Screenshots**
https://ramstik.pictures/ath-58fc9.png
https://ramstik.pictures/ath-cdad9.png
https://ramstik.pictures/ath-7d29b.png

**Release information (please complete the following information):**
 - Windows 10
 - x64
 - 2022.09.24.0

**Comment by AAndyProgram** [comment]
It's not a bug. Indeed, SCrawler doesn't check system variables. ffmpeg must be placed in the SCrawler path.

>Program should check local folder first for the existence of ffmpeg.exe, and then it should check user and system environment variables to see if it exists elsewhere on the system.

Actually, no. You can use another developer's version of ffmpeg. ffmpeg might be a different version too. Versions may differ in commands and functions.

**This will not be implemented.** Sorry.

**Comment by reichbc** [comment]
chock this up to being the first program i've ever seen that won't allow the end user the choice of what installation of a dependency to use. If you're not going to offer the *choice* to to the users, then bundle the version of ffmpeg you want with the program.

**Comment by AAndyProgram** [comment]
Excuse me, which choice do you want? At the end of the description of each release I have posted, I give links where you can download the version of ffmpeg that I used. I don't understand what the problem is.

![image](https://user-images.githubusercontent.com/88590076/192126109-e6790afb-720f-41f0-9763-4cd8b876ca1a.png)

Btw, SCrawler works even without ffmpeg. ffmpeg is only needed to download videos hosted on Reddit and create images for video in the feed.

**Comment by AAndyProgram** [comment]
I forgot, ffmpeg is also needed to download videos from xvideos.
