### ISSUE TITLE
TikTok only downloads the latest 30 posts

### ISSUE THREAD

**Issue by AAndyProgram** [AAndyProgram/SCrawler#75]
TikTok is currently parsed through HTML. I tried to write a request which returns me a json response. But with any combination of options, I got the same response.
The request has a ```cursor``` parameter. This parameter means date in json format. Every response returns a ```cursor``` value that developer should use to get the next media data block. But this parameter is deprecated on their side or doesn't work at all. I haven't seen any requests in the browser's DevTools containing this parameter.

If you know how to solve this issue, you can post a suggestion in a comment on this post.

**Comment by OMGerEDU** [comment]
Hey there, 
I think I know your problem, 
The problem is that the "Lazy loader" only loads the X videos the website set,
I had the same problem with Twitter on the past, what you need to do is to set a task to browse down on the website until it find new posts, meanwhile save all posts (I used Xpath and compare titles VS old ones, but Tiktok is different)

**Comment by AAndyProgram** [comment]
Any code sample (link or code text) to see how it works?

**Comment by AAndyProgram** [comment]
Fixed. Please update to the [latest release](https://github.com/AAndyProgram/SCrawler/releases/latest).
